Repository RedHatQE/openshift-cluster-management-python-wrapper, pull requests merged in 2023-06, with the labels that each got.

#53 Use billing-model as standard for ROSA installation only
  ocm_python_wrapper/cluster.py
Labels: size/XS, branch-main, verified, Approved-by-rnetser, Approved-by-myakove, can-be-merged

#59 Make addon_parameters to always be dict
  ocm_python_wrapper/cluster.py
Labels: size/XS, branch-main, verified

#55 Use sampler for rosa cli
  ocm_python_wrapper/cluster.py
Labels: branch-main, verified, size/S, Approved-by-myakove, can-be-merged

#62 Edit OWNERS file
  OWNERS
Labels: size/XS, branch-main, verified, Approved-by-myakove, can-be-merged

#64 Fix get required addon parameters
  ocm_python_wrapper/cluster.py
Labels: branch-main, verified, Approved-by-rnetser, size/M, can-be-merged

#71 Update ROSA calls with client and region
  ocm_python_wrapper/cluster.py
Labels: branch-main, verified, size/S, Approved-by-myakove, can-be-merged

#73 Update OWNERS
  OWNERS
Labels: size/XS, branch-main, verified, Approved-by-myakove, Approved-by-oharan2, can-be-merged
