Repository RedHatQE/openshift-cluster-management-python-wrapper, pull requests merged in 2023-08, with the labels that each got.

#91 Update README
  README.md
Labels: size/XS, branch-main, verified, can-be-merged, ApprovedBy-rnetser

#102 Add OSD cluster creation
  ocm_python_wrapper/cluster.py
  ocm_python_wrapper/ocm_client.py
Labels: branch-main, size/L, verified, can-be-merged, ApprovedBy-myakove

#104 Add versions support
  ocm_python_wrapper/versions.py
Labels: branch-main, verified, size/S, can-be-merged, ApprovedBy-myakove

#106 Add wait for cluster operators and docstrings
  ocm_python_wrapper/cluster.py
  ocm_python_wrapper/ocm_client.py
Labels: branch-main, size/L, verified, can-be-merged, ApprovedBy-myakove
