Repository RedHatQE/openshift-cluster-management-python-wrapper, pull requests merged in 2023-09, with the labels that each got.

#108 Update wait_for_cluster_operators_progressing_false arg name
  ocm_python_wrapper/cluster.py
Labels: branch-main, verified, size/M, can-be-merged, ApprovedBy-myakove, CommentedBy-myakove

#119 Cluster: Remove cluster_id call from __init__
  ocm_python_wrapper/cluster.py
Labels: branch-main, verified, size/M, can-be-merged, ApprovedBy-rnetser

#121 Add `wait_exists` to Cluster class
  ocm_python_wrapper/cluster.py
Labels: branch-main, verified, size/S, can-be-merged, ApprovedBy-rnetser

#133 move to openshift-python-utilities 5.0
  poetry.lock
  pyproject.toml
Labels: branch-main, size/L, verified

#146 Add OSD GCP support
  ocm_python_wrapper/cluster.py
Labels: branch-main, verified, size/M, can-be-merged, ApprovedBy-myakove
