Repository RedHatQE/openshift-cluster-management-python-wrapper, pull requests merged in 2023-03, with the labels that each got.

#4 Install/uninstall cluster addons
  .github/stale.yml
  .isort.cfg
  .pre-commit-config.yaml
  ocm_python_wrapper/cluster.py
  ocm_python_wrapper/ocm_client.py
  pyproject.toml
  setup.py
Labels: branch-main, size/L, verified, Approved-by-rnetser

#6 Add validations for parameters
  ocm_python_wrapper/cluster.py
Labels: branch-main, verified, Approved-by-rnetser, size/M

#8 Dockerfile and python entrypoint
  ocm_python_wrapper/cluster.py
  ocm_python_wrapper/logger.py
  ocm_python_wrapper/ocm_client.py
Labels: branch-main, size/L, verified

#10 Cluster - add cluster deletion
  ocm_python_wrapper/cluster.py
Labels: branch-main, size/S, Approved-by-myakove

#12 cluster kubeconfig - add workaround for hyershift
  ocm_python_wrapper/cluster.py
Labels: size/XS, branch-main, verified, Approved-by-myakove

#19 Fix wait_for_cluster_ready log
  ocm_python_wrapper/cluster.py
Labels: size/XS, branch-main, verified

#21 cluster kubeconfig - fix var name
  ocm_python_wrapper/cluster.py
Labels: verified, Approved-by-myakove

#22 Replace setup.cfg and setup.py
  .gitignore
  .release-it.json
  README.md
  VERSION
  pyproject.toml
  setup.cfg
  setup.py
Labels: branch-main, size/L, verified, Approved-by-myakove
