Repository RedHatQE/openshift-cluster-management-python-wrapper, pull requests merged in 2023-05, with the labels that each got.

#30 update to use simple python logger
  ocm_python_wrapper/cluster.py
  ocm_python_wrapper/logger.py
  ocm_python_wrapper/ocm_client.py
Labels: branch-main, verified, size/M, Approved-by-myakove

#32 Fix RHMI patching
  ocm_python_wrapper/cluster.py
Labels: size/XS, branch-main, verified, Approved-by-myakove

#35 Support for RHODS brew configuration
  ocm_python_wrapper/cluster.py
Labels: branch-main, verified, Approved-by-rnetser, size/S, Approved-by-myakove

#41 receive brew token (str) instead of brew pull secret dict
  ocm_python_wrapper/cluster.py
Labels: branch-main, verified, Approved-by-rnetser, size/S, Approved-by-myakove

#39 Support install/uninstall addon via rosa cli
  ocm_python_wrapper/cluster.py
  pyproject.toml
Labels: branch-main, verified, Approved-by-rnetser, size/M, Approved-by-myakove

#47 Add python-simple-logger to pyproject.toml
  pyproject.toml
Labels: size/XS, branch-main, verified, Approved-by-myakove

#45 Use cloud tools for RHOAM installation
  ocm_python_wrapper/cluster.py
  ocm_python_wrapper/manifests/managed-api-service-policy.json
  pyproject.toml
Labels: branch-main, verified, Approved-by-rnetser, size/M, Approved-by-myakove, can-be-merged

#51 Support for addon parameters before installation
  ocm_python_wrapper/cluster.py
  pyproject.toml
Labels: branch-main, size/L, verified, Approved-by-myakove, can-be-merged
